# Exported from Render on 2025-06-26T07:00:15Z
services:
- type: web
  name: EVoting-App
  runtime: python
  repo: https://github.com/VickyKumar001/EVoting-App
  plan: free
  region: oregon
  buildCommand: sh build.sh
  startCommand: gunicorn myvoting.wsgi:application
  autoDeployTrigger: commit
version: "1"
